export class ImHausListe {
  zimmernummer: string;
  anreise: string;
  abreise: string;
  name1: string;
  nameFrau1: string;
  nation1: string;
  pinfo1: string;
  aufenthalte1: string;
  letzterAufenthalt1: string;
  name2: string;
  nameFrau2: string;
  nation2: string;
  pinfo2: string;
  aufenthalte2: string;
  letzterAufenthalt2: string;
  name3: string;
  nameFrau3: string;
  nation3: string;
  pinfo3: string;
  aufenthalte3: string;
  letzterAufenthalt3: string;
  name4: string;
  nameFrau4: string;
  nation4: string;
  pinfo4: string;
  aufenthalte4: string;
  letzterAufenthalt4: string;
  personenAnzahl:string;
  isAnreise: boolean;
}
